// 
// Do not edit this file, it is automatically generated!
// To generate this file, "make design.h" in the rtl directory.
// 
#ifndef DESIGN_H
#define DESIGN_H

#define	INCLUDE_ZIPCPU
#define	WBUBUS_MASTER
#define	SDRAM_ACCESS
#define	WATCHDOG_ACCESS
#define	GPIO_ACCESS
#define	BUSCONSOLE_ACCESS
#define	BUSTIMER_ACCESS
#define	BKRAM_ACCESS
#define	BUSPIC_ACCESS
#ifdef	SDRAM_ACCESS
#define	SDRAM_SCOPE
#endif	// SDRAM_ACCESS
#ifdef	SDRAM_SCOPE
#else	// SDRAM_SCOPE
#endif	// SDRAM_SCOPE
#ifdef	SDRAM_ACCESS
#else	// SDRAM_ACCESS
#endif	// SDRAM_ACCESS
#ifdef	INCLUDE_ZIPCPU
#else	// INCLUDE_ZIPCPU
#endif	// INCLUDE_ZIPCPU
#ifdef	WATCHDOG_ACCESS
#else	// WATCHDOG_ACCESS
#endif	// WATCHDOG_ACCESS
#ifdef	GPIO_ACCESS
#else	// GPIO_ACCESS
#endif	// GPIO_ACCESS
#ifdef	WBUBUS_MASTER
#ifndef	BUSPIC_ACCESS
#endif
#else	// WBUBUS_MASTER
#endif	// WBUBUS_MASTER
#ifdef	INCLUDE_ZIPCPU
#else
#endif	// INCLUDE_ZIPCPU
#ifdef	WBUBUS_MASTER
#ifdef	INCLUDE_ZIPCPU
#define	BUS_DELAY_NEEDED
#endif
#endif
#ifdef	BUS_DELAY_NEEDED
#else
#endif
#ifdef	INCLUDE_ZIPCPU
#endif
#ifdef	BUSCONSOLE_ACCESS
#else	// BUSCONSOLE_ACCESS
#endif	// BUSCONSOLE_ACCESS
#ifdef	BUSTIMER_ACCESS
#else	// BUSTIMER_ACCESS
#endif	// BUSTIMER_ACCESS
#ifdef	BKRAM_ACCESS
#else	// BKRAM_ACCESS
#endif	// BKRAM_ACCESS
#ifdef	BUSPIC_ACCESS
#else	// BUSPIC_ACCESS
#endif	// BUSPIC_ACCESS

#endif // DESIGN_H
